version: '3.8'

services:
  app:
    build: .
    container_name: task-chest
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/postgres

  postgres:
    image: postgres:latest
    container_name: bd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"

